# Generated by Django 5.0.6 on 2024-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("drama", "Drama"),
                    ("comedy", "Comedy"),
                    ("history", "History"),
                    ("news", "News"),
                    ("thriller", "Thriller"),
                    ("horror", "Horror"),
                ],
                default="--select--",
            ),
        ),
    ]
