# Generated by Django 5.0.6 on 2024-06-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="jaswanth", max_length=20),
        ),
    ]
