# Generated by Django 5.0.6 on 2025-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("action", "Action"),
                    ("drama", "Drama"),
                    ("comedy", "Comedy"),
                    ("history", "History"),
                    ("news", "News"),
                    ("thriller", "Thriller"),
                    ("horror", "Horror"),
                    ("fantasy", "Fantasy"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
