# Generated by Django 5.0.6 on 2024-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.FileField(upload_to="static/"),
        ),
    ]
