# Generated by Django 5.0.6 on 2024-06-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(default="New", max_length=20),
        ),
    ]
